insert into CATEGORIA (nombre) values ('Sioux');
insert into CATEGORIA (nombre) values ('Taiwanese');
insert into CATEGORIA (nombre) values ('Colombian');
insert into CATEGORIA (nombre) values ('Seminole');
insert into CATEGORIA (nombre) values ('Venezuelan');
insert into CATEGORIA (nombre) values ('Native Hawaiian and Other Pacific Islander (NHPI)');
insert into CATEGORIA (nombre) values ('Potawatomi');
insert into CATEGORIA (nombre) values ('Cuban');
insert into CATEGORIA (nombre) values ('Puerto Rican');
insert into CATEGORIA (nombre) values ('Aleut');
insert into CATEGORIA (nombre) values ('Central American');
insert into CATEGORIA (nombre) values ('Filipino');
insert into CATEGORIA (nombre) values ('Ute');
insert into CATEGORIA (nombre) values ('Fijian');
insert into CATEGORIA (nombre) values ('Ottawa');
insert into CATEGORIA (nombre) values ('Cheyenne');
insert into CATEGORIA (nombre) values ('Chippewa');
insert into CATEGORIA (nombre) values ('Sri Lankan');
insert into CATEGORIA (nombre) values ('Melanesian');
insert into CATEGORIA (nombre) values ('Bangladeshi');
