
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Aleut', 'Flowdesk', 'Kwinu');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Aleut', 'Lotstring', 'Gigabox');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Aleut', 'Namfix', 'Realpoint');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Aleut', 'Toughjoyfax', 'Eayo');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Bangladeshi', 'Alpha', 'Jetwire');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Bangladeshi', 'Bamity', 'Trunyx');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Bangladeshi', 'Fintone', 'Katz');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Bangladeshi', 'Flexidy', 'Zoomzone');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Bangladeshi', 'Konklab', 'Jaxworks');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Bangladeshi', 'Matsoft', 'Voonyx');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Bangladeshi', 'Redhold', 'Realcube');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Central American', 'Alphazap', 'Vitz');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Central American', 'Bitwolf', 'Tagcat');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Central American', 'Lotstring', 'Reallinks');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Central American', 'Pannier', 'Vinder');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Cheyenne', 'Otcom', 'Cogilith');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Cheyenne', 'Zoolab', 'Linkbuzz');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Chippewa', 'Opela', 'Edgeclub');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Chippewa', 'Prodder', 'Tazz');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Chippewa', 'Ronstring', 'Edgeclub');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Chippewa', 'Toughjoyfax', 'Skyba');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Chippewa', 'Voyatouch', 'Realcube');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Colombian', 'Alphazap', 'Photobean');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Colombian', 'Asoka', 'Quamba');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Colombian', 'Gembucket', 'Zoomdog');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Colombian', 'Lotlux', 'Tagcat');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Colombian', 'Overhold', 'Dabshots');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Colombian', 'Sub-Ex', 'Tagchat');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Colombian', 'Tin', 'Pixonyx');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Cuban', 'Bitwolf', 'Tagcat');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Cuban', 'Cardguard', 'Topicstorm');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Cuban', 'Zontrax', 'Katz');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Fijian', 'Fintone', 'Voolith');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Fijian', 'Flexidy', 'Zoomzone');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Fijian', 'Flowdesk', 'Kwinu');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Fijian', 'Keylex', 'LiveZ');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Fijian', 'Pannier', 'Voonyx');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Fijian', 'Redhold', 'Browsedrive');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Fijian', 'Sub-Ex', 'Tagchat');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Fijian', 'Tres-Zap', 'Eayo');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Filipino', 'Alphazap', 'Vitz');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Filipino', 'Overhold', 'Voolith');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Filipino', 'Sub-Ex', 'Realblab');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Filipino', 'Toughjoyfax', 'Meeveo');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Filipino', 'Zaam-Dox', 'Ntag');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Melanesian', 'Lotlux', 'Tagcat');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Melanesian', 'Prodder', 'Pixonyx');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Melanesian', 'Redhold', 'Oyope');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Melanesian', 'Stim', 'Quamba');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Melanesian', 'Y-find', 'Eidel');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Native Hawaiian and Other Pacific Islander (NHPI)', 'Bitwolf', 'Reallinks');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Native Hawaiian and Other Pacific Islander (NHPI)', 'Cardguard', 'Zoomlounge');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Native Hawaiian and Other Pacific Islander (NHPI)', 'Konklab', 'Miboo');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Native Hawaiian and Other Pacific Islander (NHPI)', 'Pannier', 'Voonyx');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Native Hawaiian and Other Pacific Islander (NHPI)', 'Tin', 'Pixonyx');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Native Hawaiian and Other Pacific Islander (NHPI)', 'Vagram', 'Oyoyo');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Native Hawaiian and Other Pacific Islander (NHPI)', 'Zontrax', 'Katz');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Native Hawaiian and Other Pacific Islander (NHPI)', 'Zoolab', 'Voonyx');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Ottawa', 'Bitwolf', 'Gigabox');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Ottawa', 'Sub-Ex', 'Realblab');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Ottawa', 'Voyatouch', 'Riffpath');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Ottawa', 'Y-Solowarm', 'Kaymbo');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Potawatomi', 'Bigtax', 'Ntag');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Potawatomi', 'Flowdesk', 'Twinder');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Potawatomi', 'Lotstring', 'Reallinks');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Potawatomi', 'Otcom', 'Snaptags');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Potawatomi', 'Tampflex', 'Snaptags');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Puerto Rican', 'Flowdesk', 'Kwinu');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Puerto Rican', 'Flowdesk', 'Twinder');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Puerto Rican', 'Overhold', 'Dabshots');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Puerto Rican', 'Ronstring', 'Mymm');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Seminole', 'Bamity', 'Trunyx');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Seminole', 'Fintone', 'Voolith');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Seminole', 'Gembucket', 'Topicshots');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Seminole', 'Sonsing', 'Tagchat');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Seminole', 'Y-find', 'LiveZ');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Sioux', 'Bigtax', 'Ntag');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Sioux', 'Bitwolf', 'Reallinks');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Sioux', 'Bytecard', 'Voonder');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Sioux', 'Hatity', 'Mycat');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Sioux', 'Vagram', 'Oyoyo');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Sri Lankan', 'Bytecard', 'Voonder');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Sri Lankan', 'Fix San', 'Roodel');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Sri Lankan', 'Pannier', 'Vinder');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Sri Lankan', 'Sonair', 'Realblab');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Sri Lankan', 'Zoolab', 'Linkbuzz');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Taiwanese', 'Bitwolf', 'Reallinks');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Taiwanese', 'Cardguard', 'Topicstorm');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Taiwanese', 'Home Ing', 'Kwinu');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Ute', 'Fix San', 'Bubblemix');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Ute', 'Prodder', 'Tazz');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Venezuelan', 'Cardguard', 'Topicstorm');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Venezuelan', 'Flexidy', 'Zoomzone');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Venezuelan', 'Flowdesk', 'Kwinu');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Venezuelan', 'Flowdesk', 'Voonyx');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Venezuelan', 'Konklab', 'Jaxworks');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Venezuelan', 'Konklux', 'Innotype');
insert into CATEGORIA_MENU (nombre_categoria, nombre_menu, nombre_restaurante) values ('Venezuelan', 'Stringtough', 'Skyba');