
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Aleut', 1);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Aleut', 25);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Aleut', 47);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Aleut', 58);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Aleut', 6);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Aleut', 79);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Bangladeshi', 10);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Bangladeshi', 12);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Bangladeshi', 14);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Bangladeshi', 2);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Bangladeshi', 27);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Bangladeshi', 32);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Bangladeshi', 35);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Bangladeshi', 40);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Bangladeshi', 49);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Bangladeshi', 53);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Bangladeshi', 69);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Bangladeshi', 7);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Bangladeshi', 70);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Bangladeshi', 76);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Bangladeshi', 77);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Bangladeshi', 82);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Central American', 11);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Central American', 23);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Central American', 44);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Central American', 5);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Central American', 54);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Central American', 63);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Central American', 75);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Central American', 9);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Cheyenne', 16);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Cheyenne', 35);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Cheyenne', 44);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Cheyenne', 51);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Cheyenne', 7);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Chippewa', 9);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Chippewa', 92);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Colombian', 22);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Colombian', 39);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Colombian', 61);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Colombian', 99);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Cuban', 2);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Cuban', 63);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Cuban', 78);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Fijian', 11);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Fijian', 48);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Filipino', 34);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Filipino', 74);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Filipino', 8);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Melanesian', 11);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Melanesian', 36);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Melanesian', 38);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Melanesian', 40);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Melanesian', 71);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Melanesian', 90);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Native Hawaiian and Other Pacific Islander (NHPI)', 17);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Native Hawaiian and Other Pacific Islander (NHPI)', 9);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Native Hawaiian and Other Pacific Islander (NHPI)', 93);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Ottawa', 28);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Ottawa', 33);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Ottawa', 42);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Ottawa', 5);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Ottawa', 9);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Potawatomi', 17);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Potawatomi', 30);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Potawatomi', 46);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Potawatomi', 67);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Potawatomi', 97);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Puerto Rican', 10);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Puerto Rican', 100);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Puerto Rican', 12);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Puerto Rican', 15);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Puerto Rican', 34);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Seminole', 18);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Seminole', 21);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Seminole', 47);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Seminole', 58);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Sioux', 15);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Sioux', 45);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Sioux', 7);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Sioux', 81);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Sioux', 89);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Sioux', 91);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Sri Lankan', 68);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Sri Lankan', 69);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Sri Lankan', 72);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Sri Lankan', 75);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Sri Lankan', 78);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Taiwanese', 73);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Ute', 26);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Ute', 27);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Ute', 43);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Ute', 65);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Ute', 88);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Venezuelan', 2);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Venezuelan', 26);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Venezuelan', 31);
insert into CATEGORIA_PRODUCTO (nombre_categoria, id_producto) values ('Venezuelan', 64);
