insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Aleut', 'Babbleset');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Aleut', 'Jetpulse');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Aleut', 'LiveZ');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Aleut', 'Oyope');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Aleut', 'Pixonyx');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Aleut', 'Rhyloo');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Aleut', 'Skilith');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Bangladeshi', 'Gigabox');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Bangladeshi', 'Innotype');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Bangladeshi', 'Oyoyo');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Bangladeshi', 'Photobean');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Bangladeshi', 'Vinder');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Central American', 'Demivee');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Central American', 'Kaymbo');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Central American', 'Oyoyo');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Central American', 'Wikido');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Cheyenne', 'Bubblemix');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Cheyenne', 'Cogilith');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Cheyenne', 'Dabshots');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Cheyenne', 'Pixoboo');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Cheyenne', 'Reallinks');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Cheyenne', 'Skilith');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Cheyenne', 'Topicstorm');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Cheyenne', 'Voonyx');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Chippewa', 'Devpoint');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Chippewa', 'Jetpulse');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Colombian', 'Gabspot');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Colombian', 'Quamba');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Colombian', 'Topicshots');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Colombian', 'Voonyx');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Colombian', 'Youbridge');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Cuban', 'Bubblemix');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Cuban', 'Demimbu');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Cuban', 'Linkbuzz');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Cuban', 'Photobean');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Cuban', 'Photojam');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Cuban', 'Quatz');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Fijian', 'Fanoodle');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Fijian', 'Kanoodle');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Fijian', 'Oyope');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Fijian', 'Pixonyx');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Fijian', 'Zoomdog');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Filipino', 'Edgeclub');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Filipino', 'Jaxworks');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Filipino', 'Skyble');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Filipino', 'Topicshots');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Melanesian', 'Mycat');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Melanesian', 'Twinder');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Native Hawaiian and Other Pacific Islander (NHPI)', 'Skipstorm');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Native Hawaiian and Other Pacific Islander (NHPI)', 'Trupe');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Native Hawaiian and Other Pacific Islander (NHPI)', 'Voonyx');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Ottawa', 'Centimia');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Ottawa', 'Gigabox');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Ottawa', 'Kanoodle');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Ottawa', 'Riffpath');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Ottawa', 'Yodo');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Potawatomi', 'Fivechat');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Potawatomi', 'Mycat');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Potawatomi', 'Tagchat');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Potawatomi', 'Topicshots');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Puerto Rican', 'Bubblemix');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Puerto Rican', 'Eayo');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Puerto Rican', 'Mycat');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Puerto Rican', 'Mymm');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Puerto Rican', 'Realblab');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Puerto Rican', 'Realcube');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Puerto Rican', 'Wikido');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Puerto Rican', 'Youbridge');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Seminole', 'Demimbu');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Seminole', 'Edgeclub');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Seminole', 'Kwinu');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Seminole', 'Mymm');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Seminole', 'Riffpath');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Seminole', 'Tagcat');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Seminole', 'Voonyx');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Seminole', 'Zoomlounge');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Sioux', 'Pixoboo');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Sioux', 'Topicshots');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Sri Lankan', 'Demimbu');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Sri Lankan', 'Gabtype');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Sri Lankan', 'Kaymbo');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Sri Lankan', 'Tazzy');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Taiwanese', 'Devpoint');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Taiwanese', 'LiveZ');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Ute', 'Cogilith');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Ute', 'Jaxworks');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Ute', 'Photojam');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Ute', 'Reallinks');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Ute', 'Voonyx');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Ute', 'Zoomlounge');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Venezuelan', 'Gabspot');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Venezuelan', 'Jetpulse');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Venezuelan', 'Realcube');
insert into CATEGORIA_RESTAURANTE (nombre_categoria, nombre_restaurante) values ('Venezuelan', 'Skipstorm');

