insert into CONDICIONZONA (condiciontecnicanombre, zonanombre) values ('Mandatory', 'Jewelery');
insert into CONDICIONZONA (condiciontecnicanombre, zonanombre) values ('Face to face', 'Computers');
insert into CONDICIONZONA (condiciontecnicanombre, zonanombre) values ('Mandatory', 'Baby');
insert into CONDICIONZONA (condiciontecnicanombre, zonanombre) values ('productivity', 'Sports');
insert into CONDICIONZONA (condiciontecnicanombre, zonanombre) values ('Stand-alone', 'Beauty');
insert into CONDICIONZONA (condiciontecnicanombre, zonanombre) values ('Mandatory', 'Sports');
insert into CONDICIONZONA (condiciontecnicanombre, zonanombre) values ('Secured', 'Clothing');
insert into CONDICIONZONA (condiciontecnicanombre, zonanombre) values ('implementation', 'Games');
insert into CONDICIONZONA (condiciontecnicanombre, zonanombre) values ('implementation', 'Sports');
insert into CONDICIONZONA (condiciontecnicanombre, zonanombre) values ('Organized', 'Garden');
insert into CONDICIONZONA (condiciontecnicanombre, zonanombre) values ('implementation', 'Beauty');
insert into CONDICIONZONA (condiciontecnicanombre, zonanombre) values ('core', 'Sports');
insert into CONDICIONZONA (condiciontecnicanombre, zonanombre) values ('Innovative', 'Sports');
insert into CONDICIONZONA (condiciontecnicanombre, zonanombre) values ('Mandatory', 'Garden');
insert into CONDICIONZONA (condiciontecnicanombre, zonanombre) values ('tangible', 'Home');
insert into CONDICIONZONA (condiciontecnicanombre, zonanombre) values ('implementation', 'Garden');
insert into CONDICIONZONA (condiciontecnicanombre, zonanombre) values ('groupware', 'Beauty');
insert into CONDICIONZONA (condiciontecnicanombre, zonanombre) values ('productivity', 'Beauty');
insert into CONDICIONZONA (condiciontecnicanombre, zonanombre) values ('Face to face', 'Shoes');
insert into CONDICIONZONA (condiciontecnicanombre, zonanombre) values ('capability', 'Garden');
insert into CONDICIONZONA (condiciontecnicanombre, zonanombre) values ('productivity', 'Baby');
insert into CONDICIONZONA (condiciontecnicanombre, zonanombre) values ('groupware', 'Computers');
insert into CONDICIONZONA (condiciontecnicanombre, zonanombre) values ('architecture', 'Garden');
insert into CONDICIONZONA (condiciontecnicanombre, zonanombre) values ('implementation', 'Books');
insert into CONDICIONZONA (condiciontecnicanombre, zonanombre) values ('core', 'Baby');
insert into CONDICIONZONA (condiciontecnicanombre, zonanombre) values ('productivity', 'Music');
insert into CONDICIONZONA (condiciontecnicanombre, zonanombre) values ('Total', 'Games');
insert into CONDICIONZONA (condiciontecnicanombre, zonanombre) values ('Networked', 'Home');
insert into CONDICIONZONA (condiciontecnicanombre, zonanombre) values ('Organized', 'Games');
insert into CONDICIONZONA (condiciontecnicanombre, zonanombre) values ('architecture', 'Sports');

