insert into CONDICIONTECNICA (nombre) values ('tangible');
insert into CONDICIONTECNICA (nombre) values ('Networked');
insert into CONDICIONTECNICA (nombre) values ('Secured');
insert into CONDICIONTECNICA (nombre) values ('Multi-layered');
insert into CONDICIONTECNICA (nombre) values ('6th generation');
insert into CONDICIONTECNICA (nombre) values ('core');
insert into CONDICIONTECNICA (nombre) values ('productivity');
insert into CONDICIONTECNICA (nombre) values ('systematic');
insert into CONDICIONTECNICA (nombre) values ('Innovative');
insert into CONDICIONTECNICA (nombre) values ('implementation');
insert into CONDICIONTECNICA (nombre) values ('Mandatory');
insert into CONDICIONTECNICA (nombre) values ('Organized');
insert into CONDICIONTECNICA (nombre) values ('Open-architected');
insert into CONDICIONTECNICA (nombre) values ('capability');
insert into CONDICIONTECNICA (nombre) values ('architecture');
insert into CONDICIONTECNICA (nombre) values ('Stand-alone');
insert into CONDICIONTECNICA (nombre) values ('Face to face');
insert into CONDICIONTECNICA (nombre) values ('Total');
insert into CONDICIONTECNICA (nombre) values ('Switchable');
insert into CONDICIONTECNICA (nombre) values ('groupware');
