insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (129, 'Filipino');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (166, 'Filipino');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (160, 'Cuban');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (166, 'Taiwanese');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (168, 'Taiwanese');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (175, 'Aleut');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (128, 'Ute');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (125, 'Ute');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (161, 'Ute');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (161, 'Venezuelan');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (131, 'Chippewa');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (119, 'Filipino');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (123, 'Native Hawaiian and Other Pacific Islander (NHPI)');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (175, 'Bangladeshi');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (182, 'Fijian');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (168, 'Cheyenne');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (131, 'Bangladeshi');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (159, 'Fijian');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (192, 'Fijian');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (110, 'Potawatomi');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (150, 'Cuban');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (137, 'Fijian');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (127, 'Ottawa');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (123, 'Cheyenne');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (160, 'Seminole');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (147, 'Filipino');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (191, 'Colombian');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (159, 'Native Hawaiian and Other Pacific Islander (NHPI)');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (110, 'Cuban');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (139, 'Venezuelan');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (189, 'Sri Lankan');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (173, 'Fijian');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (110, 'Colombian');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (114, 'Ute');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (102, 'Colombian');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (186, 'Seminole');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (111, 'Chippewa');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (114, 'Taiwanese');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (104, 'Filipino');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (141, 'Cuban');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (130, 'Venezuelan');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (123, 'Potawatomi');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (148, 'Melanesian');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (190, 'Central American');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (170, 'Cheyenne');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (151, 'Chippewa');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (122, 'Colombian');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (109, 'Fijian');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (139, 'Bangladeshi');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (137, 'Melanesian');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (135, 'Cheyenne');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (154, 'Melanesian');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (183, 'Chippewa');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (107, 'Sioux');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (148, 'Ottawa');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (193, 'Cuban');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (180, 'Melanesian');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (118, 'Filipino');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (165, 'Melanesian');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (192, 'Chippewa');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (118, 'Cheyenne');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (193, 'Puerto Rican');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (113, 'Sri Lankan');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (101, 'Native Hawaiian and Other Pacific Islander (NHPI)');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (129, 'Ute');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (147, 'Native Hawaiian and Other Pacific Islander (NHPI)');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (177, 'Sioux');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (164, 'Potawatomi');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (140, 'Native Hawaiian and Other Pacific Islander (NHPI)');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (176, 'Aleut');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (125, 'Colombian');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (152, 'Ute');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (167, 'Ottawa');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (163, 'Filipino');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (168, 'Melanesian');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (127, 'Seminole');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (123, 'Puerto Rican');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (119, 'Central American');
insert into PREFERENCIACATEGORIA (idusuario, nombrecategoria) values (152, 'Colombian');
