--BORRA TODO EN LA BD

--REINICIA LAS SECUENCIAS


--CREACIÓN EN EL ORDEN DADO
--ROL (SOLO SE PUEDE INSERTAR OPERADORES)
INSERT INTO ROL VALUES ('LOCAL');
INSERT INTO ROL VALUES ('CLIENTE');
INSERT INTO ROL VALUES ('ORGANIZADORES');
INSERT INTO ROL VALUES ('PROVEEDOR');

--TIPOS_DE_PLATO (SOLO SE PUEDE INSERTAR BEBIDA)
INSERT INTO TIPOS_DE_PLATO VALUES ('ACOMPAÑAMIENTO');
INSERT INTO TIPOS_DE_PLATO VALUES ('PLATO FUERTE');
INSERT INTO TIPOS_DE_PLATO VALUES ('ENTRADA');
INSERT INTO TIPOS_DE_PLATO VALUES ('POSTRE');

--CONDICIONES TÉCNICAS DIFERENTES
INSERT INTO CONDICIONTECNICA VALUES ('TIENE RAMPAS');
INSERT INTO CONDICIONTECNICA VALUES ('ESCALERAS');
INSERT INTO CONDICIONTECNICA VALUES ('ESPACIO DE LISIADOS');
INSERT INTO CONDICIONTECNICA VALUES ('AIRE LIBRE');
INSERT INTO CONDICIONTECNICA VALUES ('TELEVISIONES');
INSERT INTO CONDICIONTECNICA VALUES ('VENTILADORES');
INSERT INTO CONDICIONTECNICA VALUES ('SIN CONDICIÓN');
INSERT INTO CONDICIONTECNICA VALUES ('MESEROS');
INSERT INTO CONDICIONTECNICA VALUES ('AUTOSERVICIO');
INSERT INTO CONDICIONTECNICA VALUES ('VARIOS');

--CATEGORÍAS DIFERENTES
INSERT INTO CATEGORIA VALUES ('MEXICANO');
INSERT INTO CATEGORIA VALUES ('AMERICANO');
INSERT INTO CATEGORIA VALUES ('EXPRÉS');
INSERT INTO CATEGORIA VALUES ('COLOMBIANO');
INSERT INTO CATEGORIA VALUES ('ITALIANO');
INSERT INTO CATEGORIA VALUES ('HINDÚ');
INSERT INTO CATEGORIA VALUES ('ÁRABE');
INSERT INTO CATEGORIA VALUES ('PICANTE');
INSERT INTO CATEGORIA VALUES ('DULCE');
INSERT INTO CATEGORIA VALUES ('RARO');
